# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='file',
            field=models.FileField(default=None, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
